[tool.poetry]
name = "prod"
version = "0.1.0"
description = ""
authors = ["Мартин Анкру <votb02511@yandex.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
