[tool.poetry]
name = "prod"
version = "0.1.0"
description = "shopapp"
authors = ["Martin"]
license = "MIT"


[tool.poetry.dependencies]
python = "3.8.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
